# Generated by Django 6.0.7 on 2026-07-17 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('nepali_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('diet_tag', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Eggetarian', 'Eggetarian')], default='Vegetarian', max_length=20)),
                ('suitable_meals', models.CharField(default='Breakfast,Lunch,Dinner', max_length=100)),
                ('calories', models.FloatField(default=0)),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('omega3_g', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('portion_grams', models.FloatField(default=100)),
                ('household_measure', models.CharField(default='100g serving', max_length=100)),
                ('price_tier', models.IntegerField(default=2)),
                ('available_year_round', models.BooleanField(default=True)),
                ('region_mountain', models.BooleanField(default=True)),
                ('region_hills', models.BooleanField(default=True)),
                ('region_terai', models.BooleanField(default=True)),
                ('nutrient_estimate_source', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='core.dayplan')),
            ],
            options={
                'unique_together': {('day_plan', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.FloatField(default=1)),
                ('grams', models.FloatField(default=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dayplan',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.mealplan'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderate', 'Moderate'), ('Very Active', 'Very Active'), ('Extra Active', 'Extra Active')], max_length=20)),
                ('goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Maintenance', 'Maintenance'), ('Muscle Gain', 'Muscle Gain'), ('Healthy Living', 'Healthy Living')], max_length=20)),
                ('food_preference', models.CharField(default='Vegetarian', max_length=20)),
                ('medical_conditions', models.CharField(blank=True, default='', max_length=200)),
                ('allergies', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(default='Hills', max_length=20)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('tdee', models.FloatField(blank=True, null=True)),
                ('target_calories', models.FloatField(blank=True, null=True)),
                ('target_protein_g', models.FloatField(blank=True, null=True)),
                ('target_carbs_g', models.FloatField(blank=True, null=True)),
                ('target_fat_g', models.FloatField(blank=True, null=True)),
                ('target_fiber_g', models.FloatField(blank=True, null=True)),
                ('target_omega3_g', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mealplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='core.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('meal_plan', 'day_number')},
        ),
    ]
